apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample3-deployment
  labels:
    app: sample3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample3
  template:
    metadata:
      labels:
        app: sample3
    spec:
      containers:
      - name: sample3
        image: nginx
        ports:
        - containerPort: 80

        envFrom:
        - configMapRef:
            name: app-config
