apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-nginx-config
  namespace: techmart-dev
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;

        location /health {
            default_type text/plain;
            return 200 "Backend API is Healthy";
        }

        location /ready {
            default_type text/plain;
            return 200 "Backend API is Ready to Serve";
        }
    }
