apiVersion: v1
kind: PersistentVolume
metadata:
  name: techmart-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/techmart-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: techmart-db-pvc
  namespace: techmart-dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
