apiVersion: v1
kind: Secret
metadata:
  name: database-credentials-secret
  namespace: techmart-dev
type: Opaque
stringData:
  mysql-root-password: "TechMartSecureRootPass2026"
  mysql-user: "techmart_admin"
  mysql-password: "AdminSecurePassword2026"
