apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-retain
  namespace: techmart-dev
provisioner: ebs.csi.aws.com

parameters:
  type: gp3

allowVolumeExpansion: true

volumeBindingMode: WaitForFirstConsumer

reclaimPolicy: Retain
