apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: pavan-ns-hju2026
type: Opaque
stringData:
  mysql-root-password: root123
  mysql-user: clouduser
  mysql-password: cloudpass123
