apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudvault-developer
  namespace: pavan-ns-hju2026
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudvault-operator
  namespace: pavan-ns-hju2026
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudvault-admin
  namespace: pavan-ns-hju2026
