apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermarket-deployment
  labels:
    app: frontend-supermarket
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend-supermarket
  template:
    metadata:
      labels:
        app: frontend-supermarket
    spec:
      containers:
      - name: frontend-super
        image: pavan73384/supermarket:smfV2
        ports:
        - containerPort: 3000
