apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: cloudvault-dev
  labels:
    app: frontend
    tier: web
    environment: dev
    version: v1.0
spec:
  containers:
  - name: frontend-pod
    image: nginx:1.21
    ports:
    - containerPort: 80

